server:
  port: 8761

spring:
  application:
    name: eureka-server
  freemarker: # configs for Eureka UI
    prefer-file-system-access: false

# Standalone Mode
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/